### ISSUE TITLE
UnexpectedError: Error initializing tested program

### ISSUE THREAD

**Issue by aaaaaa2493** [hyperskill/hs-test#109]
Solution: https://stepik.org/submissions/600613/322567004
Feedback:
```
Unexpected error in test #1

We have recorded this bug and will fix it soon.

Submitted via IDE

OS Windows 10
Java 11.0.8
Vendor JetBrains s.r.o.
Testing library version 7.2

org.hyperskill.hstest.exception.outcomes.UnexpectedError: Error initializing tested program
    at org.hyperskill.hstest.testing.TestedProgram.&lt;init&gt;(TestedProgram.java:110)
    at Test.lambda$generate$0(Test.java:15)
    at org.hyperskill.hstest.testing.runner.AsyncMainMethodRunner.lambda$runMain$0(AsyncMainMethodRunner.java:31)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: Format of class file incorrect for class calculator.Main : java.lang.ClassFormatError: Extra bytes at the end of class file calculator/Main
    at org.hyperskill.hstest.dynamic.DynamicClassLoader.findClass(DynamicClassLoader.java:60)
    at org.hyperskill.hstest.dynamic.DynamicClassLoader.loadClass(DynamicClassLoader.java:28)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at org.hyperskill.hstest.testing.TestedProgram.&lt;init&gt;(TestedProgram.java:105)
    ... 6 more

java.lang.ClassNotFoundException: Format of class file incorrect for class calculator.Main : java.lang.ClassFormatError: Extra bytes at the end of class file calculator/Main
    at org.hyperskill.hstest.dynamic.DynamicClassLoader.findClass(DynamicClassLoader.java:60)
    at org.hyperskill.hstest.dynamic.DynamicClassLoader.loadClass(DynamicClassLoader.java:28)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at org.hyperskill.hstest.testing.TestedProgram.&lt;init&gt;(TestedProgram.java:105)
    at Test.lambda$generate$0(Test.java:15)
    at org.hyperskill.hstest.testing.runner.AsyncMainMethodRunner.lambda$runMain$0(AsyncMainMethodRunner.java:31)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by aaaaaa2493** [comment]
Another Solution: https://stepik.org/submissions/625341/325448562
Notice that error is on stage 2
```
Unexpected error in test #2

We have recorded this bug and will fix it soon.

Submitted via IDE

OS Windows 10
Java 11.0.8
Vendor JetBrains s.r.o.
Testing library version 7.2

org.hyperskill.hstest.exception.outcomes.UnexpectedError: Error initializing tested program
    at org.hyperskill.hstest.testing.TestedProgram.&lt;init&gt;(TestedProgram.java:110)
    at JsonDatabaseTest.getServer(JsonDatabaseTest.java:444)
    at JsonDatabaseTest.checkExit(JsonDatabaseTest.java:42)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.hyperskill.hstest.dynamic.input.DynamicTesting.lambda$null$3(DynamicTesting.java:177)
    at org.hyperskill.hstest.testing.runner.AsyncMainMethodRunner.lambda$runMain$0(AsyncMainMethodRunner.java:31)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: Format of class file incorrect for class server.Main : java.lang.ClassFormatError: Truncated class file
    at org.hyperskill.hstest.dynamic.DynamicClassLoader.findClass(DynamicClassLoader.java:60)
    at org.hyperskill.hstest.dynamic.DynamicClassLoader.loadClass(DynamicClassLoader.java:28)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at org.hyperskill.hstest.testing.TestedProgram.&lt;init&gt;(TestedProgram.java:105)
    ... 12 more

java.lang.ClassNotFoundException: Format of class file incorrect for class server.Main : java.lang.ClassFormatError: Truncated class file
    at org.hyperskill.hstest.dynamic.DynamicClassLoader.findClass(DynamicClassLoader.java:60)
    at org.hyperskill.hstest.dynamic.DynamicClassLoader.loadClass(DynamicClassLoader.java:28)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at org.hyperskill.hstest.testing.TestedProgram.&lt;init&gt;(TestedProgram.java:105)
    at JsonDatabaseTest.getServer(JsonDatabaseTest.java:444)
    at JsonDatabaseTest.checkExit(JsonDatabaseTest.java:42)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.hyperskill.hstest.dynamic.input.DynamicTesting.lambda$null$3(DynamicTesting.java:177)
    at org.hyperskill.hstest.testing.runner.AsyncMainMethodRunner.lambda$runMain$0(AsyncMainMethodRunner.java:31)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by aaaaaa2493** [comment]
https://stepik.org/submissions/625339/324122362
```
Unexpected error in test #1

We have recorded this bug and will fix it soon.

Submitted via IDE

OS Windows 10
Java 11.0.8
Vendor JetBrains s.r.o.
Testing library version 7.2

org.hyperskill.hstest.exception.outcomes.UnexpectedError: Error initializing tested program
    at org.hyperskill.hstest.testing.TestedProgram.&lt;init&gt;(TestedProgram.java:110)
    at JsonDatabaseTest.getServer(JsonDatabaseTest.java:156)
    at JsonDatabaseTest.checkExit(JsonDatabaseTest.java:31)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.hyperskill.hstest.dynamic.input.DynamicTesting.lambda$null$3(DynamicTesting.java:177)
    at org.hyperskill.hstest.testing.runner.AsyncMainMethodRunner.lambda$runMain$0(AsyncMainMethodRunner.java:31)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: Format of class file incorrect for class server.Main : java.lang.ClassFormatError: Truncated class file
    at org.hyperskill.hstest.dynamic.DynamicClassLoader.findClass(DynamicClassLoader.java:60)
    at org.hyperskill.hstest.dynamic.DynamicClassLoader.loadClass(DynamicClassLoader.java:28)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at org.hyperskill.hstest.testing.TestedProgram.&lt;init&gt;(TestedProgram.java:105)
    ... 12 more

java.lang.ClassNotFoundException: Format of class file incorrect for class server.Main : java.lang.ClassFormatError: Truncated class file
    at org.hyperskill.hstest.dynamic.DynamicClassLoader.findClass(DynamicClassLoader.java:60)
    at org.hyperskill.hstest.dynamic.DynamicClassLoader.loadClass(DynamicClassLoader.java:28)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at org.hyperskill.hstest.testing.TestedProgram.&lt;init&gt;(TestedProgram.java:105)
    at JsonDatabaseTest.getServer(JsonDatabaseTest.java:156)
    at JsonDatabaseTest.checkExit(JsonDatabaseTest.java:31)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.hyperskill.hstest.dynamic.input.DynamicTesting.lambda$null$3(DynamicTesting.java:177)
    at org.hyperskill.hstest.testing.runner.AsyncMainMethodRunner.lambda$runMain$0(AsyncMainMethodRunner.java:31)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by aaaaaa2493** [comment]
https://stepik.org/submissions/625342/310487477
```
Unexpected error in test #1

We have recorded this bug and will fix it soon.

Submitted via IDE

OS Windows 10
Java 11.0.8
Vendor JetBrains s.r.o.
Testing library version 7.2

org.hyperskill.hstest.exception.outcomes.UnexpectedError: 
    at org.hyperskill.hstest.dynamic.input.DynamicTesting.lambda$null$3(DynamicTesting.java:175)
    at org.hyperskill.hstest.testing.runner.AsyncMainMethodRunner.lambda$runMain$0(AsyncMainMethodRunner.java:31)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: server/Main
    at JsonDatabaseTest.getServer(JsonDatabaseTest.java:320)
    at JsonDatabaseTest.checkExit(JsonDatabaseTest.java:91)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.hyperskill.hstest.dynamic.input.DynamicTesting.lambda$null$3(DynamicTesting.java:170)
    ... 5 more
Caused by: java.lang.ClassNotFoundException: server.Main
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    ... 12 more

java.lang.NoClassDefFoundError: server/Main
    at JsonDatabaseTest.getServer(JsonDatabaseTest.java:320)
    at JsonDatabaseTest.checkExit(JsonDatabaseTest.java:91)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.hyperskill.hstest.dynamic.input.DynamicTesting.lambda$null$3(DynamicTesting.java:170)
    at org.hyperskill.hstest.testing.runner.AsyncMainMethodRunner.lambda$runMain$0(AsyncMainMethodRunner.java:31)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: server.Main
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    ... 12 more
```

**Comment by aaaaaa2493** [comment]
java.lang.NoClassDefFoundError: bullscows/Main
https://stepik.org/submissions/624610/331962650

**Comment by aaaaaa2493** [comment]
https://stepik.org/submissions/1684027/356097867
```
Unexpected error in test #1

We have recorded this bug and will fix it soon.

Submitted via IDE

OS Windows 10
Java 11.0.9
Vendor JetBrains s.r.o.
Testing library version 8

org.hyperskill.hstest.exception.outcomes.UnexpectedError: Cannot invoke the method &quot;CinemaTests.test&quot;.
    at org.hyperskill.hstest.common.ReflectionUtils.invokeMethod(ReflectionUtils.java:90)
    at org.hyperskill.hstest.dynamic.input.DynamicTesting.lambda$null$1(DynamicTesting.java:276)
    at org.hyperskill.hstest.dynamic.input.DynamicTesting$1DynamicTestElement.lambda$null$0(DynamicTesting.java:244)
    at org.hyperskill.hstest.testing.runner.AsyncMainMethodRunner.lambda$runMain$0(AsyncMainMethodRunner.java:33)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: cinema/CinemaKt
    at CinemaTests.test(CinemaTests.java:12)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.hyperskill.hstest.common.ReflectionUtils.invokeMethod(ReflectionUtils.java:85)
    ... 7 more
Caused by: java.lang.ClassNotFoundException: cinema.CinemaKt
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    ... 13 more

java.lang.NoClassDefFoundError: cinema/CinemaKt
    at CinemaTests.test(CinemaTests.java:12)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.hyperskill.hstest.common.ReflectionUtils.invokeMethod(ReflectionUtils.java:85)
    at org.hyperskill.hstest.dynamic.input.DynamicTesting.lambda$null$1(DynamicTesting.java:276)
    at org.hyperskill.hstest.dynamic.input.DynamicTesting$1DynamicTestElement.lambda$null$0(DynamicTesting.java:244)
    at org.hyperskill.hstest.testing.runner.AsyncMainMethodRunner.lambda$runMain$0(AsyncMainMethodRunner.java:33)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: cinema.CinemaKt
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    ... 13 more
```

**Comment by aaaaaa2493** [comment]
https://stepik.org/submissions/903306/371809547
https://stepik.org/submissions/903306/371809705

**Comment by aaaaaa2493** [comment]
https://stepik.org/submissions/1560195/363806986

**Comment by aaaaaa2493** [comment]
https://stepik.org/submissions/2315299/491159615?search=129618680
