### ISSUE TITLE
Negative array size exception

### ISSUE THREAD

**Issue by tony-gk** [hyperskill/hs-test#69]
```
java.lang.NegativeArraySizeException: -1
	at org.hyperskill.hstest.v6.mocks.web.request.HttpRequestExecutor.executeRequest(HttpRequestExecutor.java:50)
	at org.hyperskill.hstest.v6.mocks.web.request.HttpRequestExecutor.send(HttpRequestExecutor.java:134)
	at org.hyperskill.hstest.v6.mocks.web.request.HttpRequest.send(HttpRequest.java:81)
	at tests.WebQuizEngineTest.testCreateQuiz(WebQuizEngineTest.java:77)
```

**Comment by aaaaaa2493** [comment]
Fixed in #70
